export const COUNTRIES_DATA = [
  { value: "AD", fullName: "Andorra", label: "376" },
  {
    value: "AE",
    fullName: "United Arab Emirates",
    label: "971",
  },
  { value: "AF", fullName: "Afghanistan", label: "93" },
  {
    value: "AG",
    fullName: "Antigua and Barbuda",
    label: "1-268",
  },
  { value: "AI", fullName: "Anguilla", label: "1-264" },
  { value: "AL", fullName: "Albania", label: "355" },
  { value: "AM", fullName: "Armenia", label: "374" },
  { value: "AO", fullName: "Angola", label: "244" },
  { value: "AQ", fullName: "Antarctica", label: "672" },
  { value: "AR", fullName: "Argentina", label: "54" },
  { value: "AS", fullName: "American Samoa", label: "1-684" },
  { value: "AT", fullName: "Austria", label: "43" },
  {
    value: "AU",
    fullName: "Australia",
    label: "61",
    suggested: true,
  },
  { value: "AW", fullName: "Aruba", label: "297" },
  { value: "AX", fullName: "Alland Islands", label: "358" },
  { value: "AZ", fullName: "Azerbaijan", label: "994" },
  {
    value: "BA",
    fullName: "Bosnia and Herzegovina",
    label: "387",
  },
  { value: "BB", fullName: "Barbados", label: "1-246" },
  { value: "BD", fullName: "Bangladesh", label: "880" },
  { value: "BE", fullName: "Belgium", label: "32" },
  { value: "BF", fullName: "Burkina Faso", label: "226" },
  { value: "BG", fullName: "Bulgaria", label: "359" },
  { value: "BH", fullName: "Bahrain", label: "973" },
  { value: "BI", fullName: "Burundi", label: "257" },
  { value: "BJ", fullName: "Benin", label: "229" },
  { value: "BL", fullName: "Saint Barthelemy", label: "590" },
  { value: "BM", fullName: "Bermuda", label: "1-441" },
  { value: "BN", fullName: "Brunei Darussalam", label: "673" },
  { value: "BO", fullName: "Bolivia", label: "591" },
  { value: "BR", fullName: "Brazil", label: "55" },
  { value: "BS", fullName: "Bahamas", label: "1-242" },
  { value: "BT", fullName: "Bhutan", label: "975" },
  { value: "BV", fullName: "Bouvet Island", label: "47" },
  { value: "BW", fullName: "Botswana", label: "267" },
  { value: "BY", fullName: "Belarus", label: "375" },
  { value: "BZ", fullName: "Belize", label: "501" },
  {
    value: "CA",
    fullName: "Canada",
    label: "1",
  },
  {
    value: "CC",
    fullName: "Cocos (Keeling) Islands",
    label: "61",
  },
  {
    value: "CD",
    fullName: "Congo, Democratic Republic of the",
    label: "243",
  },
  {
    value: "CF",
    fullName: "Central African Republic",
    label: "236",
  },
  {
    value: "CG",
    fullName: "Congo, Republic of the",
    label: "242",
  },
  { value: "CH", fullName: "Switzerland", label: "41" },
  { value: "CI", fullName: "Cote d'Ivoire", label: "225" },
  { value: "CK", fullName: "Cook Islands", label: "682" },
  { value: "CL", fullName: "Chile", label: "56" },
  { value: "CM", fullName: "Cameroon", label: "237" },
  { value: "CN", fullName: "China", label: "86" },
  { value: "CO", fullName: "Colombia", label: "57" },
  { value: "CR", fullName: "Costa Rica", label: "506" },
  { value: "CU", fullName: "Cuba", label: "53" },
  { value: "CV", fullName: "Cape Verde", label: "238" },
  { value: "CW", fullName: "Curacao", label: "599" },
  { value: "CX", fullName: "Christmas Island", label: "61" },
  { value: "CY", fullName: "Cyprus", label: "357" },
  { value: "CZ", fullName: "Czech Republic", label: "420" },
  {
    value: "DE",
    fullName: "Germany",
    label: "49",
  },
  { value: "DJ", fullName: "Djibouti", label: "253" },
  { value: "DK", fullName: "Denmark", label: "45" },
  { value: "DM", fullName: "Dominica", label: "1-767" },
  {
    value: "DO",
    fullName: "Dominican Republic",
    label: "1-809",
  },
  { value: "DZ", fullName: "Algeria", label: "213" },
  { value: "EC", fullName: "Ecuador", label: "593" },
  { value: "EE", fullName: "Estonia", label: "372" },
  { value: "EG", fullName: "Egypt", label: "20" },
  { value: "EH", fullName: "Western Sahara", label: "212" },
  { value: "ER", fullName: "Eritrea", label: "291" },
  { value: "ES", fullName: "Spain", label: "34" },
  { value: "ET", fullName: "Ethiopia", label: "251" },
  { value: "FI", fullName: "Finland", label: "358" },
  { value: "FJ", fullName: "Fiji", label: "679" },
  {
    value: "FK",
    fullName: "Falkland Islands (Malvinas)",
    label: "500",
  },
  {
    value: "FM",
    fullName: "Micronesia, Federated States of",
    label: "691",
  },
  { value: "FO", fullName: "Faroe Islands", label: "298" },
  {
    value: "FR",
    fullName: "France",
    label: "33",
  },
  { value: "GA", fullName: "Gabon", label: "241" },
  { value: "GB", fullName: "United Kingdom", label: "44" },
  { value: "GD", fullName: "Grenada", label: "1-473" },
  { value: "GE", fullName: "Georgia", label: "995" },
  { value: "GF", fullName: "French Guiana", label: "594" },
  { value: "GG", fullName: "Guernsey", label: "44" },
  { value: "GH", fullName: "Ghana", label: "233" },
  { value: "GI", fullName: "Gibraltar", label: "350" },
  { value: "GL", fullName: "Greenland", label: "299" },
  { value: "GM", fullName: "Gambia", label: "220" },
  { value: "GN", fullName: "Guinea", label: "224" },
  { value: "GP", fullName: "Guadeloupe", label: "590" },
  { value: "GQ", fullName: "Equatorial Guinea", label: "240" },
  { value: "GR", fullName: "Greece", label: "30" },
  {
    value: "GS",
    fullName: "South Georgia and the South Sandwich Islands",
    label: "500",
  },
  { value: "GT", fullName: "Guatemala", label: "502" },
  { value: "GU", fullName: "Guam", label: "1-671" },
  { value: "GW", fullName: "Guinea-Bissau", label: "245" },
  { value: "GY", fullName: "Guyana", label: "592" },
  { value: "HK", fullName: "Hong Kong", label: "852" },
  {
    value: "HM",
    fullName: "Heard Island and McDonald Islands",
    label: "672",
  },
  { value: "HN", fullName: "Honduras", label: "504" },
  { value: "HR", fullName: "Croatia", label: "385" },
  { value: "HT", fullName: "Haiti", label: "509" },
  { value: "HU", fullName: "Hungary", label: "36" },
  { value: "ID", fullName: "Indonesia", label: "62" },
  { value: "IE", fullName: "Ireland", label: "353" },
  { value: "IL", fullName: "Israel", label: "972" },
  { value: "IM", fullName: "Isle of Man", label: "44" },
  { value: "IN", fullName: "India", label: "91" },
  {
    value: "IO",
    fullName: "British Indian Ocean Territory",
    label: "246",
  },
  { value: "IQ", fullName: "Iraq", label: "964" },
  {
    value: "IR",
    fullName: "Iran, Islamic Republic of",
    label: "98",
  },
  { value: "IS", fullName: "Iceland", label: "354" },
  { value: "IT", fullName: "Italy", label: "39" },
  { value: "JE", fullName: "Jersey", label: "44" },
  { value: "JM", fullName: "Jamaica", label: "1-876" },
  { value: "JO", fullName: "Jordan", label: "962" },
  {
    value: "JP",
    fullName: "Japan",
    label: "81",
  },
  { value: "KE", fullName: "Kenya", label: "254" },
  { value: "KG", fullName: "Kyrgyzstan", label: "996" },
  { value: "KH", fullName: "Cambodia", label: "855" },
  { value: "KI", fullName: "Kiribati", label: "686" },
  { value: "KM", fullName: "Comoros", label: "269" },
  {
    value: "KN",
    fullName: "Saint Kitts and Nevis",
    label: "1-869",
  },
  {
    value: "KP",
    fullName: "Korea, Democratic People's Republic of",
    label: "850",
  },
  { value: "KR", fullName: "Korea, Republic of", label: "82" },
  { value: "KW", fullName: "Kuwait", label: "965" },
  { value: "KY", fullName: "Cayman Islands", label: "1-345" },
  { value: "KZ", fullName: "Kazakhstan", label: "7" },
  {
    value: "LA",
    fullName: "Lao People's Democratic Republic",
    label: "856",
  },
  { value: "LB", fullName: "Lebanon", label: "961" },
  { value: "LC", fullName: "Saint Lucia", label: "1-758" },
  { value: "LI", fullName: "Liechtenstein", label: "423" },
  { value: "LK", fullName: "Sri Lanka", label: "94" },
  { value: "LR", fullName: "Liberia", label: "231" },
  { value: "LS", fullName: "Lesotho", label: "266" },
  { value: "LT", fullName: "Lithuania", label: "370" },
  { value: "LU", fullName: "Luxembourg", label: "352" },
  { value: "LV", fullName: "Latvia", label: "371" },
  { value: "LY", fullName: "Libya", label: "218" },
  { value: "MA", fullName: "Morocco", label: "212" },
  { value: "MC", fullName: "Monaco", label: "377" },
  {
    value: "MD",
    fullName: "Moldova, Republic of",
    label: "373",
  },
  { value: "ME", fullName: "Montenegro", label: "382" },
  {
    value: "MF",
    fullName: "Saint Martin (French part)",
    label: "590",
  },
  { value: "MG", fullName: "Madagascar", label: "261" },
  { value: "MH", fullName: "Marshall Islands", label: "692" },
  {
    value: "MK",
    fullName: "Macedonia, the Former Yugoslav Republic of",
    label: "389",
  },
  { value: "ML", fullName: "Mali", label: "223" },
  { value: "MM", fullName: "Myanmar", label: "95" },
  { value: "MN", fullName: "Mongolia", label: "976" },
  { value: "MO", fullName: "Macao", label: "853" },
  {
    value: "MP",
    fullName: "Northern Mariana Islands",
    label: "1-670",
  },
  { value: "MQ", fullName: "Martinique", label: "596" },
  { value: "MR", fullName: "Mauritania", label: "222" },
  { value: "MS", fullName: "Montserrat", label: "1-664" },
  { value: "MT", fullName: "Malta", label: "356" },
  { value: "MU", fullName: "Mauritius", label: "230" },
  { value: "MV", fullName: "Maldives", label: "960" },
  { value: "MW", fullName: "Malawi", label: "265" },
  { value: "MX", fullName: "Mexico", label: "52" },
  { value: "MY", fullName: "Malaysia", label: "60" },
  { value: "MZ", fullName: "Mozambique", label: "258" },
  { value: "NA", fullName: "Namibia", label: "264" },
  { value: "NC", fullName: "New Caledonia", label: "687" },
  { value: "NE", fullName: "Niger", label: "227" },
  { value: "NF", fullName: "Norfolk Island", label: "672" },
  { value: "NG", fullName: "Nigeria", label: "234" },
  { value: "NI", fullName: "Nicaragua", label: "505" },
  { value: "NL", fullName: "Netherlands", label: "31" },
  { value: "NO", fullName: "Norway", label: "47" },
  { value: "NP", fullName: "Nepal", label: "977" },
  { value: "NR", fullName: "Nauru", label: "674" },
  { value: "NU", fullName: "Niue", label: "683" },
  { value: "NZ", fullName: "New Zealand", label: "64" },
  { value: "OM", fullName: "Oman", label: "968" },
  { value: "PA", fullName: "Panama", label: "507" },
  { value: "PE", fullName: "Peru", label: "51" },
  { value: "PF", fullName: "French Polynesia", label: "689" },
  { value: "PG", fullName: "Papua New Guinea", label: "675" },
  { value: "PH", fullName: "Philippines", label: "63" },
  { value: "PK", fullName: "Pakistan", label: "92" },
  { value: "PL", fullName: "Poland", label: "48" },
  {
    value: "PM",
    fullName: "Saint Pierre and Miquelon",
    label: "508",
  },
  { value: "PN", fullName: "Pitcairn", label: "870" },
  { value: "PR", fullName: "Puerto Rico", label: "1" },
  {
    value: "PS",
    fullName: "Palestine, State of",
    label: "970",
  },
  { value: "PT", fullName: "Portugal", label: "351" },
  { value: "PW", fullName: "Palau", label: "680" },
  { value: "PY", fullName: "Paraguay", label: "595" },
  { value: "QA", fullName: "Qatar", label: "974" },
  { value: "RE", fullName: "Reunion", label: "262" },
  { value: "RO", fullName: "Romania", label: "40" },
  { value: "RS", fullName: "Serbia", label: "381" },
  { value: "RU", fullName: "Russian Federation", label: "7" },
  { value: "RW", fullName: "Rwanda", label: "250" },
  { value: "SA", fullName: "Saudi Arabia", label: "966" },
  { value: "SB", fullName: "Solomon Islands", label: "677" },
  { value: "SC", fullName: "Seychelles", label: "248" },
  { value: "SD", fullName: "Sudan", label: "249" },
  { value: "SE", fullName: "Sweden", label: "46" },
  { value: "SG", fullName: "Singapore", label: "65" },
  { value: "SH", fullName: "Saint Helena", label: "290" },
  { value: "SI", fullName: "Slovenia", label: "386" },
  {
    value: "SJ",
    fullName: "Svalbard and Jan Mayen",
    label: "47",
  },
  { value: "SK", fullName: "Slovakia", label: "421" },
  { value: "SL", fullName: "Sierra Leone", label: "232" },
  { value: "SM", fullName: "San Marino", label: "378" },
  { value: "SN", fullName: "Senegal", label: "221" },
  { value: "SO", fullName: "Somalia", label: "252" },
  { value: "SR", fullName: "Suriname", label: "597" },
  { value: "SS", fullName: "South Sudan", label: "211" },
  {
    value: "ST",
    fullName: "Sao Tome and Principe",
    label: "239",
  },
  { value: "SV", fullName: "El Salvador", label: "503" },
  {
    value: "SX",
    fullName: "Sint Maarten (Dutch part)",
    label: "1-721",
  },
  {
    value: "SY",
    fullName: "Syrian Arab Republic",
    label: "963",
  },
  { value: "SZ", fullName: "Swaziland", label: "268" },
  {
    value: "TC",
    fullName: "Turks and Caicos Islands",
    label: "1-649",
  },
  { value: "TD", fullName: "Chad", label: "235" },

  { value: "TG", fullName: "Togo", label: "228" },
  { value: "TH", fullName: "Thailand", label: "66" },
  { value: "TJ", fullName: "Tajikistan", label: "992" },
  { value: "TK", fullName: "Tokelau", label: "690" },
  { value: "TL", fullName: "Timor-Leste", label: "670" },
  { value: "TM", fullName: "Turkmenistan", label: "993" },
  { value: "TN", fullName: "Tunisia", label: "216" },
  { value: "TO", fullName: "Tonga", label: "676" },
  { value: "TR", fullName: "Turkey", label: "90" },
  {
    value: "TT",
    fullName: "Trinidad and Tobago",
    label: "1-868",
  },
  { value: "TV", fullName: "Tuvalu", label: "688" },
  {
    value: "TW",
    fullName: "Taiwan",
    label: "886",
  },
  {
    value: "TZ",
    fullName: "United Republic of Tanzania",
    label: "255",
  },
  { value: "UA", fullName: "Ukraine", label: "380" },
  { value: "UG", fullName: "Uganda", label: "256" },
  {
    value: "US",
    fullName: "United States",
    label: "1",
    suggested: true,
  },
  { value: "UY", fullName: "Uruguay", label: "598" },
  { value: "UZ", fullName: "Uzbekistan", label: "998" },
  {
    value: "VA",
    fullName: "Holy See (Vatican City State)",
    label: "379",
  },
  {
    value: "VC",
    fullName: "Saint Vincent and the Grenadines",
    label: "1-784",
  },
  { value: "VE", fullName: "Venezuela", label: "58" },
  {
    value: "VG",
    fullName: "British Virgin Islands",
    label: "1-284",
  },
  {
    value: "VI",
    fullName: "US Virgin Islands",
    label: "1-340",
  },
  { value: "VN", fullName: "Vietnam", label: "84" },
  { value: "VU", fullName: "Vanuatu", label: "678" },
  { value: "WF", fullName: "Wallis and Futuna", label: "681" },
  { value: "WS", fullName: "Samoa", label: "685" },
  { value: "XK", fullName: "Kosovo", label: "383" },
  { value: "YE", fullName: "Yemen", label: "967" },
  { value: "ZA", fullName: "South Africa", label: "27" },
  { value: "ZM", fullName: "Zambia", label: "260" },
  { value: "ZW", fullName: "Zimbabwe", label: "263" },
];
