export const COUNTRIES_DATA_2 = [
  { value: "AD", label: "Andorra", code: "376" },
  {
    value: "AE",
    label: "United Arab Emirates",
    code: "971",
  },
  { value: "AF", label: "Afghanistan", code: "93" },
  {
    value: "AG",
    label: "Antigua and Barbuda",
    code: "1-268",
  },
  { value: "AI", label: "Anguilla", code: "1-264" },
  { value: "AL", label: "Albania", code: "355" },
  { value: "AM", label: "Armenia", code: "374" },
  { value: "AO", label: "Angola", code: "244" },
  { value: "AQ", label: "Antarctica", code: "672" },
  { value: "AR", label: "Argentina", code: "54" },
  { value: "AS", label: "American Samoa", code: "1-684" },
  { value: "AT", label: "Austria", code: "43" },
  {
    value: "AU",
    label: "Australia",
    code: "61",
    suggested: true,
  },
  { value: "AW", label: "Aruba", code: "297" },
  { value: "AX", label: "Alland Islands", code: "358" },
  { value: "AZ", label: "Azerbaijan", code: "994" },
  {
    value: "BA",
    label: "Bosnia and Herzegovina",
    code: "387",
  },
  { value: "BB", label: "Barbados", code: "1-246" },
  { value: "BD", label: "Bangladesh", code: "880" },
  { value: "BE", label: "Belgium", code: "32" },
  { value: "BF", label: "Burkina Faso", code: "226" },
  { value: "BG", label: "Bulgaria", code: "359" },
  { value: "BH", label: "Bahrain", code: "973" },
  { value: "BI", label: "Burundi", code: "257" },
  { value: "BJ", label: "Benin", code: "229" },
  { value: "BL", label: "Saint Barthelemy", code: "590" },
  { value: "BM", label: "Bermuda", code: "1-441" },
  { value: "BN", label: "Brunei Darussalam", code: "673" },
  { value: "BO", label: "Bolivia", code: "591" },
  { value: "BR", label: "Brazil", code: "55" },
  { value: "BS", label: "Bahamas", code: "1-242" },
  { value: "BT", label: "Bhutan", code: "975" },
  { value: "BV", label: "Bouvet Island", code: "47" },
  { value: "BW", label: "Botswana", code: "267" },
  { value: "BY", label: "Belarus", code: "375" },
  { value: "BZ", label: "Belize", code: "501" },
  {
    value: "CA",
    label: "Canada",
    code: "1",
  },
  {
    value: "CC",
    label: "Cocos (Keeling) Islands",
    code: "61",
  },
  {
    value: "CD",
    label: "Congo, Democratic Republic of the",
    code: "243",
  },
  {
    value: "CF",
    label: "Central African Republic",
    code: "236",
  },
  {
    value: "CG",
    label: "Congo, Republic of the",
    code: "242",
  },
  { value: "CH", label: "Switzerland", code: "41" },
  { value: "CI", label: "Cote d'Ivoire", code: "225" },
  { value: "CK", label: "Cook Islands", code: "682" },
  { value: "CL", label: "Chile", code: "56" },
  { value: "CM", label: "Cameroon", code: "237" },
  { value: "CN", label: "China", code: "86" },
  { value: "CO", label: "Colombia", code: "57" },
  { value: "CR", label: "Costa Rica", code: "506" },
  { value: "CU", label: "Cuba", code: "53" },
  { value: "CV", label: "Cape Verde", code: "238" },
  { value: "CW", label: "Curacao", code: "599" },
  { value: "CX", label: "Christmas Island", code: "61" },
  { value: "CY", label: "Cyprus", code: "357" },
  { value: "CZ", label: "Czech Republic", code: "420" },
  {
    value: "DE",
    label: "Germany",
    code: "49",
  },
  { value: "DJ", label: "Djibouti", code: "253" },
  { value: "DK", label: "Denmark", code: "45" },
  { value: "DM", label: "Dominica", code: "1-767" },
  {
    value: "DO",
    label: "Dominican Republic",
    code: "1-809",
  },
  { value: "DZ", label: "Algeria", code: "213" },
  { value: "EC", label: "Ecuador", code: "593" },
  { value: "EE", label: "Estonia", code: "372" },
  { value: "EG", label: "Egypt", code: "20" },
  { value: "EH", label: "Western Sahara", code: "212" },
  { value: "ER", label: "Eritrea", code: "291" },
  { value: "ES", label: "Spain", code: "34" },
  { value: "ET", label: "Ethiopia", code: "251" },
  { value: "FI", label: "Finland", code: "358" },
  { value: "FJ", label: "Fiji", code: "679" },
  {
    value: "FK",
    label: "Falkland Islands (Malvinas)",
    code: "500",
  },
  {
    value: "FM",
    label: "Micronesia, Federated States of",
    code: "691",
  },
  { value: "FO", label: "Faroe Islands", code: "298" },
  {
    value: "FR",
    label: "France",
    code: "33",
  },
  { value: "GA", label: "Gabon", code: "241" },
  { value: "GB", label: "United Kingdom", code: "44" },
  { value: "GD", label: "Grenada", code: "1-473" },
  { value: "GE", label: "Georgia", code: "995" },
  { value: "GF", label: "French Guiana", code: "594" },
  { value: "GG", label: "Guernsey", code: "44" },
  { value: "GH", label: "Ghana", code: "233" },
  { value: "GI", label: "Gibraltar", code: "350" },
  { value: "GL", label: "Greenland", code: "299" },
  { value: "GM", label: "Gambia", code: "220" },
  { value: "GN", label: "Guinea", code: "224" },
  { value: "GP", label: "Guadeloupe", code: "590" },
  { value: "GQ", label: "Equatorial Guinea", code: "240" },
  { value: "GR", label: "Greece", code: "30" },
  {
    value: "GS",
    label: "South Georgia and the South Sandwich Islands",
    code: "500",
  },
  { value: "GT", label: "Guatemala", code: "502" },
  { value: "GU", label: "Guam", code: "1-671" },
  { value: "GW", label: "Guinea-Bissau", code: "245" },
  { value: "GY", label: "Guyana", code: "592" },
  { value: "HK", label: "Hong Kong", code: "852" },
  {
    value: "HM",
    label: "Heard Island and McDonald Islands",
    code: "672",
  },
  { value: "HN", label: "Honduras", code: "504" },
  { value: "HR", label: "Croatia", code: "385" },
  { value: "HT", label: "Haiti", code: "509" },
  { value: "HU", label: "Hungary", code: "36" },
  { value: "ID", label: "Indonesia", code: "62" },
  { value: "IE", label: "Ireland", code: "353" },
  { value: "IL", label: "Israel", code: "972" },
  { value: "IM", label: "Isle of Man", code: "44" },
  { value: "IN", label: "India", code: "91" },
  {
    value: "IO",
    label: "British Indian Ocean Territory",
    code: "246",
  },
  { value: "IQ", label: "Iraq", code: "964" },
  {
    value: "IR",
    label: "Iran, Islamic Republic of",
    code: "98",
  },
  { value: "IS", label: "Iceland", code: "354" },
  { value: "IT", label: "Italy", code: "39" },
  { value: "JE", label: "Jersey", code: "44" },
  { value: "JM", label: "Jamaica", code: "1-876" },
  { value: "JO", label: "Jordan", code: "962" },
  {
    value: "JP",
    label: "Japan",
    code: "81",
  },
  { value: "KE", label: "Kenya", code: "254" },
  { value: "KG", label: "Kyrgyzstan", code: "996" },
  { value: "KH", label: "Cambodia", code: "855" },
  { value: "KI", label: "Kiribati", code: "686" },
  { value: "KM", label: "Comoros", code: "269" },
  {
    value: "KN",
    label: "Saint Kitts and Nevis",
    code: "1-869",
  },
  {
    value: "KP",
    label: "Korea, Democratic People's Republic of",
    code: "850",
  },
  { value: "KR", label: "Korea, Republic of", code: "82" },
  { value: "KW", label: "Kuwait", code: "965" },
  { value: "KY", label: "Cayman Islands", code: "1-345" },
  { value: "KZ", label: "Kazakhstan", code: "7" },
  {
    value: "LA",
    label: "Lao People's Democratic Republic",
    code: "856",
  },
  { value: "LB", label: "Lebanon", code: "961" },
  { value: "LC", label: "Saint Lucia", code: "1-758" },
  { value: "LI", label: "Liechtenstein", code: "423" },
  { value: "LK", label: "Sri Lanka", code: "94" },
  { value: "LR", label: "Liberia", code: "231" },
  { value: "LS", label: "Lesotho", code: "266" },
  { value: "LT", label: "Lithuania", code: "370" },
  { value: "LU", label: "Luxembourg", code: "352" },
  { value: "LV", label: "Latvia", code: "371" },
  { value: "LY", label: "Libya", code: "218" },
  { value: "MA", label: "Morocco", code: "212" },
  { value: "MC", label: "Monaco", code: "377" },
  {
    value: "MD",
    label: "Moldova, Republic of",
    code: "373",
  },
  { value: "ME", label: "Montenegro", code: "382" },
  {
    value: "MF",
    label: "Saint Martin (French part)",
    code: "590",
  },
  { value: "MG", label: "Madagascar", code: "261" },
  { value: "MH", label: "Marshall Islands", code: "692" },
  {
    value: "MK",
    label: "Macedonia, the Former Yugoslav Republic of",
    code: "389",
  },
  { value: "ML", label: "Mali", code: "223" },
  { value: "MM", label: "Myanmar", code: "95" },
  { value: "MN", label: "Mongolia", code: "976" },
  { value: "MO", label: "Macao", code: "853" },
  {
    value: "MP",
    label: "Northern Mariana Islands",
    code: "1-670",
  },
  { value: "MQ", label: "Martinique", code: "596" },
  { value: "MR", label: "Mauritania", code: "222" },
  { value: "MS", label: "Montserrat", code: "1-664" },
  { value: "MT", label: "Malta", code: "356" },
  { value: "MU", label: "Mauritius", code: "230" },
  { value: "MV", label: "Maldives", code: "960" },
  { value: "MW", label: "Malawi", code: "265" },
  { value: "MX", label: "Mexico", code: "52" },
  { value: "MY", label: "Malaysia", code: "60" },
  { value: "MZ", label: "Mozambique", code: "258" },
  { value: "NA", label: "Namibia", code: "264" },
  { value: "NC", label: "New Caledonia", code: "687" },
  { value: "NE", label: "Niger", code: "227" },
  { value: "NF", label: "Norfolk Island", code: "672" },
  { value: "NG", label: "Nigeria", code: "234" },
  { value: "NI", label: "Nicaragua", code: "505" },
  { value: "NL", label: "Netherlands", code: "31" },
  { value: "NO", label: "Norway", code: "47" },
  { value: "NP", label: "Nepal", code: "977" },
  { value: "NR", label: "Nauru", code: "674" },
  { value: "NU", label: "Niue", code: "683" },
  { value: "NZ", label: "New Zealand", code: "64" },
  { value: "OM", label: "Oman", code: "968" },
  { value: "PA", label: "Panama", code: "507" },
  { value: "PE", label: "Peru", code: "51" },
  { value: "PF", label: "French Polynesia", code: "689" },
  { value: "PG", label: "Papua New Guinea", code: "675" },
  { value: "PH", label: "Philippines", code: "63" },
  { value: "PK", label: "Pakistan", code: "92" },
  { value: "PL", label: "Poland", code: "48" },
  {
    value: "PM",
    label: "Saint Pierre and Miquelon",
    code: "508",
  },
  { value: "PN", label: "Pitcairn", code: "870" },
  { value: "PR", label: "Puerto Rico", code: "1" },
  {
    value: "PS",
    label: "Palestine, State of",
    code: "970",
  },
  { value: "PT", label: "Portugal", code: "351" },
  { value: "PW", label: "Palau", code: "680" },
  { value: "PY", label: "Paraguay", code: "595" },
  { value: "QA", label: "Qatar", code: "974" },
  { value: "RE", label: "Reunion", code: "262" },
  { value: "RO", label: "Romania", code: "40" },
  { value: "RS", label: "Serbia", code: "381" },
  { value: "RU", label: "Russian Federation", code: "7" },
  { value: "RW", label: "Rwanda", code: "250" },
  { value: "SA", label: "Saudi Arabia", code: "966" },
  { value: "SB", label: "Solomon Islands", code: "677" },
  { value: "SC", label: "Seychelles", code: "248" },
  { value: "SD", label: "Sudan", code: "249" },
  { value: "SE", label: "Sweden", code: "46" },
  { value: "SG", label: "Singapore", code: "65" },
  { value: "SH", label: "Saint Helena", code: "290" },
  { value: "SI", label: "Slovenia", code: "386" },
  {
    value: "SJ",
    label: "Svalbard and Jan Mayen",
    code: "47",
  },
  { value: "SK", label: "Slovakia", code: "421" },
  { value: "SL", label: "Sierra Leone", code: "232" },
  { value: "SM", label: "San Marino", code: "378" },
  { value: "SN", label: "Senegal", code: "221" },
  { value: "SO", label: "Somalia", code: "252" },
  { value: "SR", label: "Suriname", code: "597" },
  { value: "SS", label: "South Sudan", code: "211" },
  {
    value: "ST",
    label: "Sao Tome and Principe",
    code: "239",
  },
  { value: "SV", label: "El Salvador", code: "503" },
  {
    value: "SX",
    label: "Sint Maarten (Dutch part)",
    code: "1-721",
  },
  {
    value: "SY",
    label: "Syrian Arab Republic",
    code: "963",
  },
  { value: "SZ", label: "Swaziland", code: "268" },
  {
    value: "TC",
    label: "Turks and Caicos Islands",
    code: "1-649",
  },
  { value: "TD", label: "Chad", code: "235" },

  { value: "TG", label: "Togo", code: "228" },
  { value: "TH", label: "Thailand", code: "66" },
  { value: "TJ", label: "Tajikistan", code: "992" },
  { value: "TK", label: "Tokelau", code: "690" },
  { value: "TL", label: "Timor-Leste", code: "670" },
  { value: "TM", label: "Turkmenistan", code: "993" },
  { value: "TN", label: "Tunisia", code: "216" },
  { value: "TO", label: "Tonga", code: "676" },
  { value: "TR", label: "Turkey", code: "90" },
  {
    value: "TT",
    label: "Trinidad and Tobago",
    code: "1-868",
  },
  { value: "TV", label: "Tuvalu", code: "688" },
  {
    value: "TW",
    label: "Taiwan",
    code: "886",
  },
  {
    value: "TZ",
    label: "United Republic of Tanzania",
    code: "255",
  },
  { value: "UA", label: "Ukraine", code: "380" },
  { value: "UG", label: "Uganda", code: "256" },
  {
    value: "US",
    label: "United States",
    code: "1",
    suggested: true,
  },
  { value: "UY", label: "Uruguay", code: "598" },
  { value: "UZ", label: "Uzbekistan", code: "998" },
  {
    value: "VA",
    label: "Holy See (Vatican City State)",
    code: "379",
  },
  {
    value: "VC",
    label: "Saint Vincent and the Grenadines",
    code: "1-784",
  },
  { value: "VE", label: "Venezuela", code: "58" },
  {
    value: "VG",
    label: "British Virgin Islands",
    code: "1-284",
  },
  {
    value: "VI",
    label: "US Virgin Islands",
    code: "1-340",
  },
  { value: "VN", label: "Vietnam", code: "84" },
  { value: "VU", label: "Vanuatu", code: "678" },
  { value: "WF", label: "Wallis and Futuna", code: "681" },
  { value: "WS", label: "Samoa", code: "685" },
  { value: "XK", label: "Kosovo", code: "383" },
  { value: "YE", label: "Yemen", code: "967" },
  { value: "ZA", label: "South Africa", code: "27" },
  { value: "ZM", label: "Zambia", code: "260" },
  { value: "ZW", label: "Zimbabwe", code: "263" },
];
