import {
  CATEGORY_NON_ICON,
  CATEGORY_HOME_ICON,
  CATEGORY_CONDOMINIUM_ICON,
  CATEGORY_APARTMENT_ICON,
  CATEGORY_TOWNHOUSE_ICON,
  CATEGORY_DORM_ICON,
  CATEGORY_ADD_ICON,
} from "../assets/icons/PropertyCategoryIcons";

export const PROPERTY_CATEGORY_ICONS = [
  { id: "1", Icon: CATEGORY_NON_ICON },
  { id: "2", Icon: CATEGORY_HOME_ICON },
  { id: "3", Icon: CATEGORY_CONDOMINIUM_ICON },
  { id: "4", Icon: CATEGORY_APARTMENT_ICON },
  { id: "5", Icon: CATEGORY_TOWNHOUSE_ICON },
  { id: "6", Icon: CATEGORY_DORM_ICON },
  { id: "7", Icon: CATEGORY_ADD_ICON },
];
